const archiver = require('archiver');
const path = require('path');

/**
 * Stream a ZIP containing all downloaded files to the HTTP response.
 *
 * @param {http.ServerResponse} res   - Express response object
 * @param {Map<string, Buffer>} files - filePath → Buffer
 * @param {object} meta               - { siteName, manifest, brokenLinks, readmeContent }
 */
/**
 * Stream a ZIP containing all downloaded files to the HTTP response.
 */
async function streamZip(res, files, meta = {}) {
  const {
    siteName = 'pixelpack-download',
    manifest = [],
    brokenLinks = [],
    readmeContent = '',
  } = meta;

  const safeZipName = siteName.replace(/[^a-z0-9_.-]/gi, '-').toLowerCase();

  // Set headers
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${safeZipName}.zip"`);

  return new Promise((resolve, reject) => {
    const archive = archiver('zip', {
      zlib: { level: 6 },
      forceLocalTime: true,
    });

    archive.on('error', (err) => {
      console.error('Archiver error:', err);
      reject(err);
    });

    archive.on('warning', (warn) => {
      if (warn.code === 'ENOENT') {
        console.warn('Archiver warning (ENOENT):', warn);
      } else {
        console.error('Archiver error:', warn);
        reject(warn);
      }
    });

    // Pipe archive data to the response
    archive.pipe(res);

    // Add files from the Map
    const usedPaths = new Set();
    for (const [filePath, buffer] of files) {
      if (usedPaths.has(filePath)) continue;
      usedPaths.add(filePath);
      archive.append(buffer, { name: `${safeZipName}/${filePath}` });
    }

    // Add metadata
    if (readmeContent) {
      archive.append(readmeContent, { name: `${safeZipName}/_pixelpack/README.md` });
    }

    if (manifest.length > 0) {
      archive.append(JSON.stringify(manifest, null, 2), {
        name: `${safeZipName}/_pixelpack/manifest.json`,
      });
    }

    if (brokenLinks.length > 0) {
      const brokenContent = Array.isArray(brokenLinks) ? brokenLinks.join('\n') : String(brokenLinks);
      archive.append(brokenContent, {
        name: `${safeZipName}/_pixelpack/broken-links.txt`,
      });
    }

    // Finalize the archive (this is when the Central Directory is written)
    archive.finalize().catch(reject);

    // Resolve when both archive is done and response has flushed
    let archiveEnded = false;
    let resFinished = false;

    const checkDone = () => {
      if (archiveEnded && resFinished) {
        console.log(`[ZIP] Successfully finalized and streamed. Total bytes: ${archive.pointer()}`);
        resolve();
      }
    };

    archive.on('end', () => {
      archiveEnded = true;
      checkDone();
    });

    res.on('finish', () => {
      resFinished = true;
      checkDone();
    });
  });
}

/**
 * Build a README.md string for the _pixelpack metadata folder
 */
function buildReadme(startUrl, pages, assetCount, brokenCount, capturedTypes) {
  const now = new Date().toISOString();
  return `# PixelPack — Capture Report

**Source URL:** ${startUrl}
**Captured At:** ${now}
**Total Pages Crawled:** ${pages.length}
**Total Assets Downloaded:** ${assetCount}
**Broken / Failed Links:** ${brokenCount}

## Asset Types Captured
${capturedTypes.map(([type, count]) => `- ${type}: ${count} files`).join('\n')}

## Notes
- This ZIP was generated by PixelPack for educational and design research purposes.
- Some assets may be missing if they are protected, dynamically generated, or streamed.
- JavaScript-rendered content and API-fetched data are not included.
- Always respect the original website's Terms of Service and copyright.

## Offline Compatibility
Simple HTML/CSS/JS sites will work largely offline. React/Vue/Angular apps may require their build toolchain to function fully.

---
*Generated by PixelPack v1.0*
`;
}

/**
 * Build a manifest array for the _pixelpack/manifest.json
 */
function buildManifest(assetUrls, files) {
  return [...assetUrls.entries()].map(([url, category]) => {
    const filePath = files.has(url) ? url : null;
    return { url, category, downloaded: files.has(url), filePath };
  });
}

module.exports = { streamZip, buildReadme, buildManifest };
